spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee_management}
    username: ${DB_USERNAME:employee_management}
    password: ${DB_PASSWORD:employee_management}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.example.employeemanagement: INFO
